name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        # Replace with your build commands
        echo "Building the source code"
        
    - name: Test
      run: |
        # Replace with your test commands
        echo "Running unit tests and code quality checks"
    
    - name: Deploy to Staging
      run: |
        # Replace with your deployment commands
        echo "Deploying to staging environment"

  notify-failure:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
    - name: Send failure notification
      uses: appleboy/telegram-action@v1
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "Build or deployment failed for the project."
